spring:
  application:
    name: Design Software
  datasource:
    driver-class-name: org.postgresql.Driver
    username: user
    password: user
    url: jdbc:postgresql://localhost:5432/postgres

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true